services:
  mongo:
    image: mongo:latest
    container_name: database-mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge